Step 1: upgrade SBT plugins in project/plugins.sbt
It is possible that there may be a number of HMRC SBT plugins that require updating to Play 2.5 compatible versions. Ensure you are using the latest. However, the most important thing is that you upgrade Typesafe's sbt-plugin to version 2.5.8.

It is most likely that you will need to update:

1. addSbtPlugin("uk.gov.hmrc" % "sbt-distributables" % "1.0.0")

2. addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.8")

NOTE: This change will break your project. If you are using IntelliJ with auto-import of SBT projects, you will probably see a project import error along the lines of:

Error:Error while importing SBT project:<br/>...<br/><pre>[info] Resolving org.scala-sbt#main-settings;0.13.11 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.11 ...
[info] Resolving org.scala-sbt#command;0.13.11 ...
[info] Resolving org.scala-sbt#logic;0.13.11 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.11 ...
[info] Resolving org.scala-lang#jline;2.10.6 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 2 Scala sources to /your-microservice/project/target/scala-2.10/sbt-0.13/classes...
[error] /your-microservice/project/MicroService.scala:26: object PlayScala is not a member of package play
[error]     .enablePlugins(Seq(play.PlayScala,SbtAutoBuildPlugin, SbtGitVersioning, SbtDistributablesPlugin) ++ plugins : _*)
[error]                             ^
[error] /your-microservice/project/MicroServiceBuild.scala:14: object PlayImport is not a member of package play
[error]   import play.PlayImport._
[error]               ^
[error] /your-microservice/project/MicroServiceBuild.scala:31: not found: value ws
[error]     ws,
[error]     ^